#RealMLP-TD-S standalone implementation

In [ ]:
!pip install openml             #for machine learning

Requirement already satisfied: openml in /usr/local/lib/python3.13/dist-packages (0.15.1)
Requirement already satisfied: liac-arff>=2.4.0 in /usr/local/lib/python3.13/dist-packages (from openml) (2.5.0)
Requirement already satisfied: xmltodict in /usr/local/lib/python3.13/dist-packages (from openml) (1.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from openml) (2.32.4)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.13/dist-packages (from openml) (1.6.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.13/dist-packages (from openml) (2.9.0.post0)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from openml) (2.2.3)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/lib/python3.13/dist-packages (from openml) (1.16.3)
Requirement already satisfied: numpy>=1.6.2 in /usr/local/lib/python3.13/dist-packages (from openml) (2.1.3)
Requirement already satisfied: minio in /usr/local/lib/python3.13/dist-packages (from openml) (7.2.20)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.13/dist-packages (from openml) (23.0.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from openml) (4.67.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from openml) (26.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->openml) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->openml) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil->openml) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.18->openml) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.18->openml) (3.7.0)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.13/dist-packages (from minio->openml) (25.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from minio->openml) (2026.7.22)
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.13/dist-packages (from minio->openml) (4.0.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.13/dist-packages (from minio->openml) (4.16.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from minio->openml) (2.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->openml) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->openml) (3.20)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=0.18->openml) (3.1.2)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.13/dist-packages (from argon2-cffi->minio->openml) (26.1.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from argon2-cffi-bindings->argon2-cffi->minio->openml) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->minio->openml) (3.0)

In [ ]:
import openml
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
task = openml.tasks.get_task(361113)

dataset = openml.datasets.get_dataset(task.dataset_id, download_data=False)
X, y, categorical_indicator, attribute_names = dataset.get_data(
    dataset_format='dataframe',
    target=task.target_name,
)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=15000, random_state=0
)
X_test = X_test[:10000]
y_test = y_test[:10000]

In [ ]:
X_train

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
257550,3023.0,131.0,9,150.0,22.0,2766.0,235,235,132,488.0,...,0,0,0,0,0,0,0,0,0,0
348903,2992.0,8.0,22,234.0,47.0,2981.0,190,192,133,1531.0,...,0,0,1,0,0,0,0,0,0,0
174868,2813.0,62.0,10,270.0,29.0,2409.0,229,219,122,1403.0,...,0,0,0,0,0,0,0,0,0,0
345725,3259.0,198.0,28,351.0,66.0,684.0,199,250,168,1036.0,...,0,0,0,0,0,0,0,0,0,0
89391,3125.0,310.0,15,323.0,56.0,324.0,179,229,190,1355.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359783,3182.0,315.0,36,324.0,153.0,2948.0,104,185,208,2856.0,...,0,0,1,0,0,0,0,0,0,0
358083,3305.0,1.0,18,371.0,29.0,999.0,191,202,146,2501.0,...,0,0,0,0,0,0,0,1,0,0
152315,2910.0,43.0,11,255.0,37.0,3231.0,222,215,126,2743.0,...,0,0,0,0,0,0,0,0,0,0
117952,2673.0,71.0,12,335.0,3.0,1138.0,233,216,113,1642.0,...,0,0,0,0,0,0,0,0,0,0
305711,3030.0,49.0,11,90.0,3.0,1593.0,224,217,125,1101.0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
y_train

257550    2
348903    2
174868    1
345725    2
89391     1
         ..
359783    2
358083    2
152315    1
117952    1
305711    2
Name: class, Length: 15000, dtype: category
Categories (2, object): ['1' < '2']

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
X_train = X_train.astype(float).values
X_test = X_test.astype(float).values
y_train = y_train.astype(float).values
y_test = y_test.astype(float).values

In [ ]:
model = MLPClassifier(hidden_layer_sizes=(100, 200, 100))

model.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(100, 200, 100))

In [ ]:
accuracy_score(y_test, model.predict(X_test))

0.7729

##Download (clone) git repo

In [ ]:
!git clone https://github.com/dholzmueller/realmlp-td-s_standalone.git

#clone github here

fatal: destination path 'realmlp-td-s_standalone' already exists and is not an empty directory.

In [ ]:
!mv realmlp-td-s_standalone/*.py .

#save repositories

In [ ]:
from mlp import Standalone_RealMLP_TD_S_Classifier

In [ ]:
import re, pathlib
for fname in ['mlp.py', 'preprocessing.py']:
    p = pathlib.Path(fname)
    text = p.read_text()
    text = re.sub(r'np\.NaN', 'np.nan', text)
    text = re.sub(r'np\.Inf', 'np.inf', text)
    p.write_text(text)

In [ ]:
from importlib import reload
import mlp
reload(mlp)
from mlp import Standalone_RealMLP_TD_S_Classifier

In [ ]:
accuracy_score(y_test, Standalone_RealMLP_TD_S_Classifier(model).predict(X_test)

_IncompleteInputError: incomplete input (4136752086.py, line 1)